import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";


const monstrate = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cavalo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monstrate.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
